### ISSUE TITLE
minor issue in document of Counter example

### ISSUE THREAD

**Issue by wenwei202** [leptonai/examples#40]
`c = client.Client(local())`

should be 

`c = Client(local())`

in 

https://www.lepton.ai/docs/walkthrough/anatomy_of_a_photon

error
```
>>> from leptonai.client import Client, local
>>> c = client.Client(local())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'client' is not defined
```

**Comment by bddppq** [comment]
Thanks for reporting, a fix has been committed and will be rolled out soon.

**Comment by bddppq** [comment]
Fixed
